# Site settings
title: Charlie Knudsen
email: charlie.knudsen@gmail.com
description: "Charlie Knudsen's Blog"
baseurl: ""
url: "http://www.charlieknudsen.com"
twitter_username: cjknudsen
github_username:  charliek

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments